application: routee-secudev
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /font-awesome
  static_dir: font-awesome

- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: /js
  static_dir: js  

- url: /dbControl\.php
  script: dbControl.php

- url: /encrypt\.php
  script: encrypt.php

- url: /loginController\.php
  script: loginController.php

- url: /logoutController\.php
  script: logoutController.php

- url: /register\.php
  script: register.php

- url: /registerController\.php
  script: registerController.php

- url: /routee\.php
  script: routee.php

- url: /index\.php
  script: index.php

- url: .*
  script: index.php
